FROM ubuntu:16.04

ARG BINTRAYKEY
ARG TRAVIS_JOB_NUMBER 

# Setup
RUN apt-get update -y -qq
RUN apt-get install -y apt-utils -qq
RUN apt-get install -y git gcc g++ autotools-dev dh-autoreconf cmake cmake-data curl -qq
RUN apt-get install -y qt5-default qtbase5-dev-tools qtdeclarative5-dev -qq
RUN apt-get update -y -qq
RUN mkdir -p /src/
RUN git clone https://github.com/aymara/qhttpserver /src/qhttpserver

RUN mkdir -p /src/qhttpserver/build
 
# Build
WORKDIR /src/qhttpserver/build
RUN cmake ..
RUN make -j4
RUN make package
RUN curl -T /src/qhttpserver/build/qhttpserver-0.0.1-Linux.deb \
  -ukleag:$BINTRAYKEY \
  https://api.bintray.com/content/kleag/ubuntu-16.04/qhttpserver/$TRAVIS_JOB_NUMBER/$TRAVIS_JOB_NUMBER/qhttpserver-0.0.1-Linux.deb
RUN curl -XPOST -ukleag:$BINTRAYKEY \
  https://api.bintray.com/content/kleag/ubuntu-16.04/qhttpserver/$TRAVIS_JOB_NUMBER/publish
