FROM debian:9.4

ARG TRAVIS_JOB_NUMBER 

# Setup
RUN apt-get update -y -qq
RUN apt-get install -y apt-utils wget bzip2 git gcc g++ cmake cmake-data ninja-build qt5-default qtbase5-dev-tools qtdeclarative5-dev packaging-dev -qq
RUN mkdir -p /src/
RUN git clone https://github.com/aymara/qhttpserver /src/qhttpserver

RUN mkdir -p /src/qhttpserver/build
 
# Build
WORKDIR /src/qhttpserver/build
RUN cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release ..
RUN ninja all && ninja test && ninja package
RUN packagefile=$(find /src/qhttpserver/build/*.deb) \
    fullname=$(basename -- "$packagefile") \
    extension="${fullname##*.}" \
    filename="${fullname%.*}" \
    install -D $packagefile /usr/share/apps/qhttpserver/packages/$filename-debian9.4.deb

## install github-release to be able to deploy packages
#RUN wget https://github.com/aktau/github-release/releases/download/v0.7.2/linux-amd64-github-release.tar.bz2 && tar xjf linux-amd64-github-release.tar.bz2 && cp bin/linux/amd64/github-release /usr/bin
