FROM ubuntu:14.04

ARG BINTRAYKEY
ARG TRAVIS_JOB_NUMBER 

# Setup
RUN apt-get update -y -qq
RUN apt-get install -y apt-utils git gcc g++ cmake cmake-data ninja-build qt5-default qtbase5-dev-tools qtdeclarative5-dev -qq
RUN mkdir -p /src/
RUN git clone https://github.com/aymara/qhttpserver /src/qhttpserver

RUN mkdir -p /src/qhttpserver/build
 
# Build
WORKDIR /src/qhttpserver/build
RUN cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release ..
RUN ninja package
