
SET(QHTTPSERVER_INCLUDE_DIR @CMAKE_INSTALL_PREFIX@/include)
SET(QHTTPSERVER_LIBRARY_DIRS @CMAKE_INSTALL_PREFIX@/${LIB_INSTALL_DIR})

set(QHTTPSERVER_VERSION_MAJOR "0")
set(QHTTPSERVER_VERSION_MINOR "2")
set(QHTTPSERVER_VERSION_RELEASE "@VERSION_RELEASE@")

set(QHTTPSERVER_VERSION "${QHTTPSERVER_VERSION_MAJOR}.${QHTTPSERVER_VERSION_MINOR}.${QHTTPSERVER_VERSION_RELEASE}")

set(QHTTPSERVER_GENERIC_LIB_VERSION ${QHTTPSERVER_VERSION})
set(QHTTPSERVER_GENERIC_LIB_SOVERSION ${QHTTPSERVER_VERSION_MINOR})

message(STATUS "QHttpServer version  ${QHTTPSERVER_VERSION} - QHTTPSERVER_GENERIC_LIB_VERSION  ${QHTTPSERVER_GENERIC_LIB_VERSION} ")
